model_path: "Dahoas/gptneo-sft-single-context"
tokenizer_path: "EleutherAI/gpt-neo-1.3B"
num_layers_unfrozen: -1

train_args:
  output_dir: "../ckpts/gptneo-rm"
  num_train_epochs: 1
  logging_steps: 100
  save_strategy: "epoch"
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  warmup_steps: 100
  weight_decay: 0.01
  learning_rate: 1.0e-5
  save_total_limit: 1
  logging_dir: "./logs"
  fp16: False
  bf16: True

data_path: "Dahoas/rm-single-context"
trainer_type: "default"